name: Python GUI Application Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Debug Info
      run: |
        echo "Current directory:"
        dir
        echo "Source directory:"
        dir src
        echo "Assets directory:"
        dir assets
        echo "Python version:"
        python --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install PySide6==6.5.2
        pip install psutil
        pip install pyinstaller
        
    - name: Test imports
      run: |
        python -c "import PySide6; print('PySide6 imported successfully')"
        python -c "import psutil; print('psutil imported successfully')"
        
    - name: Build executable
      run: |
        pyinstaller src/limpeza_gui_final.py --onefile --noconsole
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: doguinho-clear-pro
        path: dist/*.exe
