name: Python GUI Application Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Debug Info
      run: |
        echo "Current directory:"
        dir
        echo "Source directory:"
        dir src
        echo "Python version:"
        python --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify imports
      run: |
        python -c "import PySide6; print('PySide6 version:', PySide6.__version__)"
        python -c "import psutil; print('psutil version:', psutil.__version__)"
        
    - name: Build executable
      run: |
        cd src
        python -m PyInstaller --onefile --noconsole limpeza_gui_final.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: doguinho-clear-pro
        path: src/dist/*.exe
