name: Python GUI Application Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Check file structure
      shell: cmd
      run: |
        echo "Checking repository structure..."
        echo "Root directory:"
        dir
        echo "Source directory:"
        dir src
        echo "Assets directory:"
        dir assets
        echo "Checking specific files:"
        if exist requirements.txt (
          echo "requirements.txt found in root"
          type requirements.txt
        ) else (
          echo "requirements.txt not found in root"
        )
        if exist src\requirements.txt (
          echo "requirements.txt found in src"
          type src\requirements.txt
        ) else (
          echo "requirements.txt not found in src"
        )
        if exist src\limpeza_gui_final.py (
          echo "limpeza_gui_final.py found"
        ) else (
          echo "limpeza_gui_final.py not found"
        )
        if exist assets\doguinho_icon.ico (
          echo "doguinho_icon.ico found"
        ) else (
          echo "doguinho_icon.ico not found"
        )
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install PySide6 pyinstaller
        if exist requirements.txt (pip install -r requirements.txt)
        if exist src\requirements.txt (pip install -r src\requirements.txt)
        
    - name: Build executable
      run: |
        python -m PyInstaller --onefile --windowed src\limpeza_gui_final.py
        
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: doguinho-clear-pro
        path: dist/
