name: Python GUI Application Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Debug directory structure
      run: |
        echo "Current directory:"
        dir
        echo "Contents of src directory:"
        dir src
        echo "Contents of root directory:"
        dir
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        if exist src\requirements.txt (pip install -r src\requirements.txt) else (pip install -r requirements.txt)
        pip install PySide6 pyinstaller
        
    - name: Build executable
      run: |
        if exist src\limpeza_gui_final.py (
          python -m PyInstaller --onefile --windowed --icon=assets\doguinho_icon.ico src\limpeza_gui_final.py
        ) else (
          echo "Error: src\limpeza_gui_final.py not found"
          exit 1
        )
        
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: doguinho-clear-pro
        path: dist/
