name: Python GUI Application Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install PySide6
        pip install psutil
        pip install pyinstaller
        
    - name: Test imports
      run: |
        python -c "import PySide6; print('PySide6 import successful')"
        python -c "import psutil; print('psutil import successful')"
        
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole src/limpeza_gui_final.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: doguinho-clear-pro
        path: dist/*.exe
